### ISSUE TITLE
Inversion doesn't work

### ISSUE THREAD

**Issue by ADharaUTEXAS123007** [lidongzh/TorchFWI#4]
Machine precision = 2.220D-16
 N =        51456     M =           30
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.09421D-41    |proj g|=  2.18419D+04
	Processing shot 36
	Processing shot 12
	Processing shot 0
	Processing shot 24
	Processing shot 37
	Processing shot 13
	Processing shot 1
	Processing shot 25
	Processing shot 38
	Processing shot 14
	Processing shot 2
	Processing shot 26
	Processing shot 39
	Processing shot 3
	Processing shot 15
	Processing shot 27
	Processing shot 40
	Processing shot 4
	Processing shot 16
	Processing shot 28
	Processing shot 41
	Processing shot 5
	Processing shot 17
	Processing shot 29
	Processing shot 42
	Processing shot 6
	Processing shot 18
	Processing shot 30
	Processing shot 43
	Processing shot 7
	Processing shot 19
	Processing shot 31
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 22
	Processing shot 10
	Processing shot 47
	Processing shot 35
	Processing shot 23
	Processing shot 11
	Processing shot 36
	Processing shot 0
	Processing shot 12
	Processing shot 24
	Processing shot 37
	Processing shot 1
	Processing shot 13
	Processing shot 25
	Processing shot 38
	Processing shot 2
	Processing shot 14
	Processing shot 26
	Processing shot 39
	Processing shot 3
	Processing shot 15
	Processing shot 27
	Processing shot 40
	Processing shot 4
	Processing shot 16
	Processing shot 28
	Processing shot 41
	Processing shot 5
	Processing shot 17
	Processing shot 29
	Processing shot 42
	Processing shot 6
	Processing shot 18
	Processing shot 30
	Processing shot 43
	Processing shot 7
	Processing shot 31
	Processing shot 19
	Processing shot 44
	Processing shot 8
	Processing shot 32
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 12
	Processing shot 36
	Processing shot 0
	Processing shot 24
	Processing shot 13
	Processing shot 37
	Processing shot 1
	Processing shot 25
	Processing shot 38
	Processing shot 14
	Processing shot 2
	Processing shot 26
	Processing shot 39
	Processing shot 15
	Processing shot 3
	Processing shot 27
	Processing shot 40
	Processing shot 16
	Processing shot 4
	Processing shot 28
	Processing shot 41
	Processing shot 17
	Processing shot 5
	Processing shot 29
	Processing shot 42
	Processing shot 18
	Processing shot 30
	Processing shot 6
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 35
	Processing shot 47
	Processing shot 23
	Processing shot 11
	Processing shot 0
	Processing shot 12
	Processing shot 36
	Processing shot 24
	Processing shot 1
	Processing shot 37
	Processing shot 25
	Processing shot 13
	Processing shot 2
	Processing shot 38
	Processing shot 26
	Processing shot 14
	Processing shot 39
	Processing shot 3
	Processing shot 27
	Processing shot 15
	Processing shot 40
	Processing shot 4
	Processing shot 28
	Processing shot 16
	Processing shot 41
	Processing shot 5
	Processing shot 29
	Processing shot 17
	Processing shot 42
	Processing shot 6
	Processing shot 30
	Processing shot 18
	Processing shot 43
	Processing shot 7
	Processing shot 31
	Processing shot 19
	Processing shot 44
	Processing shot 8
	Processing shot 32
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 36
	Processing shot 0
	Processing shot 12
	Processing shot 24
	Processing shot 37
	Processing shot 1
	Processing shot 13
	Processing shot 25
	Processing shot 38
	Processing shot 2
	Processing shot 14
	Processing shot 26
	Processing shot 39
	Processing shot 3
	Processing shot 27
	Processing shot 15
	Processing shot 40
	Processing shot 4
	Processing shot 28
	Processing shot 16
	Processing shot 41
	Processing shot 5
	Processing shot 29
	Processing shot 17
	Processing shot 42
	Processing shot 6
	Processing shot 30
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 36
	Processing shot 0
	Processing shot 12
	Processing shot 24
	Processing shot 37
	Processing shot 25
	Processing shot 1
	Processing shot 13
	Processing shot 38
	Processing shot 26
	Processing shot 2
	Processing shot 14
	Processing shot 39
	Processing shot 27
	Processing shot 3
	Processing shot 15
	Processing shot 40
	Processing shot 28
	Processing shot 4
	Processing shot 16
	Processing shot 41
	Processing shot 29
	Processing shot 5
	Processing shot 17
	Processing shot 42
	Processing shot 30
	Processing shot 6
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 12
	Processing shot 36
	Processing shot 24
	Processing shot 0
	Processing shot 37
	Processing shot 13
	Processing shot 25
	Processing shot 1
	Processing shot 38
	Processing shot 14
	Processing shot 26
	Processing shot 2
	Processing shot 39
	Processing shot 27
	Processing shot 15
	Processing shot 3
	Processing shot 40
	Processing shot 28
	Processing shot 16
	Processing shot 4
	Processing shot 41
	Processing shot 29
	Processing shot 17
	Processing shot 5
	Processing shot 42
	Processing shot 30
	Processing shot 18
	Processing shot 6
	Processing shot 43
	Processing shot 31
	Processing shot 19
	Processing shot 7
	Processing shot 44
	Processing shot 32
	Processing shot 20
	Processing shot 8
	Processing shot 45
	Processing shot 33
	Processing shot 21
	Processing shot 9
	Processing shot 46
	Processing shot 34
	Processing shot 22
	Processing shot 10
	Processing shot 47
	Processing shot 35
	Processing shot 23
	Processing shot 11
	Processing shot 12
	Processing shot 0
	Processing shot 36
	Processing shot 24
	Processing shot 37
	Processing shot 1
	Processing shot 13
	Processing shot 25
	Processing shot 38
	Processing shot 2
	Processing shot 14
	Processing shot 26
	Processing shot 39
	Processing shot 3
	Processing shot 27
	Processing shot 15
	Processing shot 40
	Processing shot 28
	Processing shot 4
	Processing shot 16
	Processing shot 41
	Processing shot 29
	Processing shot 5
	Processing shot 17
	Processing shot 42
	Processing shot 30
	Processing shot 6
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 36
	Processing shot 0
	Processing shot 12
	Processing shot 24
	Processing shot 37
	Processing shot 1
	Processing shot 25
	Processing shot 13
	Processing shot 38
	Processing shot 26
	Processing shot 2
	Processing shot 14
	Processing shot 39
	Processing shot 27
	Processing shot 3
	Processing shot 15
	Processing shot 40
	Processing shot 28
	Processing shot 4
	Processing shot 16
	Processing shot 41
	Processing shot 29
	Processing shot 5
	Processing shot 17
	Processing shot 42
	Processing shot 30
	Processing shot 6
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 0
	Processing shot 12
	Processing shot 36
	Processing shot 24
	Processing shot 37
	Processing shot 13
	Processing shot 1
	Processing shot 25
	Processing shot 38
	Processing shot 26
	Processing shot 14
	Processing shot 2
	Processing shot 39
	Processing shot 27
	Processing shot 3
	Processing shot 15
	Processing shot 40
	Processing shot 28
	Processing shot 4
	Processing shot 16
	Processing shot 41
	Processing shot 29
	Processing shot 5
	Processing shot 17
	Processing shot 42
	Processing shot 30
	Processing shot 6
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 0
	Processing shot 36
	Processing shot 12
	Processing shot 24
	Processing shot 37
	Processing shot 1
	Processing shot 13
	Processing shot 25
	Processing shot 38
	Processing shot 2
	Processing shot 14
	Processing shot 26
	Processing shot 39
	Processing shot 3
	Processing shot 27
	Processing shot 15
	Processing shot 40
	Processing shot 4
	Processing shot 28
	Processing shot 16
	Processing shot 41
	Processing shot 5
	Processing shot 29
	Processing shot 17
	Processing shot 42
	Processing shot 6
	Processing shot 30
	Processing shot 18
	Processing shot 43
	Processing shot 7
	Processing shot 31
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23
	Processing shot 36
	Processing shot 0
	Processing shot 24
	Processing shot 12
	Processing shot 37
	Processing shot 1
	Processing shot 25
	Processing shot 13
	Processing shot 38
	Processing shot 2
	Processing shot 26
	Processing shot 14
	Processing shot 39
	Processing shot 27
	Processing shot 3
	Processing shot 15
	Processing shot 40
	Processing shot 28
	Processing shot 4
	Processing shot 16
	Processing shot 41
	Processing shot 29
	Processing shot 5
	Processing shot 17
	Processing shot 42
	Processing shot 30
	Processing shot 6
	Processing shot 18
	Processing shot 43
	Processing shot 31
	Processing shot 7
	Processing shot 19
	Processing shot 44
	Processing shot 32
	Processing shot 8
	Processing shot 20
	Processing shot 45
	Processing shot 33
	Processing shot 9
	Processing shot 21
	Processing shot 46
	Processing shot 34
	Processing shot 10
	Processing shot 22
	Processing shot 47
	Processing shot 35
	Processing shot 11
	Processing shot 23

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
51456      1     21      1     0     0   2.184D+04   3.094D-41
  F =   3.0942071390756286E-041

ABNORMAL_TERMINATION_IN_LNSRCH                              

 Line search cannot locate an adequate point after 20 function
  and gradient evaluations.  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.

**Comment by lidongzh** [comment]
> Machine precision = 2.220D-16
> N = 51456 M = 30
> This problem is unconstrained.
> 
> At X0 0 variables are exactly at the bounds
> 
> At iterate 0 f= 3.09421D-41 |proj g|= 2.18419D+04
> Processing shot 36
> Processing shot 12
> Processing shot 0
> Processing shot 24
> Processing shot 37
> Processing shot 13
> Processing shot 1
> Processing shot 25
> Processing shot 38
> Processing shot 14
> Processing shot 2
> Processing shot 26
> Processing shot 39
> Processing shot 3
> Processing shot 15
> Processing shot 27
> Processing shot 40
> Processing shot 4
> Processing shot 16
> Processing shot 28
> Processing shot 41
> Processing shot 5
> Processing shot 17
> Processing shot 29
> Processing shot 42
> Processing shot 6
> Processing shot 18
> Processing shot 30
> Processing shot 43
> Processing shot 7
> Processing shot 19
> Processing shot 31
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 22
> Processing shot 10
> Processing shot 47
> Processing shot 35
> Processing shot 23
> Processing shot 11
> Processing shot 36
> Processing shot 0
> Processing shot 12
> Processing shot 24
> Processing shot 37
> Processing shot 1
> Processing shot 13
> Processing shot 25
> Processing shot 38
> Processing shot 2
> Processing shot 14
> Processing shot 26
> Processing shot 39
> Processing shot 3
> Processing shot 15
> Processing shot 27
> Processing shot 40
> Processing shot 4
> Processing shot 16
> Processing shot 28
> Processing shot 41
> Processing shot 5
> Processing shot 17
> Processing shot 29
> Processing shot 42
> Processing shot 6
> Processing shot 18
> Processing shot 30
> Processing shot 43
> Processing shot 7
> Processing shot 31
> Processing shot 19
> Processing shot 44
> Processing shot 8
> Processing shot 32
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 12
> Processing shot 36
> Processing shot 0
> Processing shot 24
> Processing shot 13
> Processing shot 37
> Processing shot 1
> Processing shot 25
> Processing shot 38
> Processing shot 14
> Processing shot 2
> Processing shot 26
> Processing shot 39
> Processing shot 15
> Processing shot 3
> Processing shot 27
> Processing shot 40
> Processing shot 16
> Processing shot 4
> Processing shot 28
> Processing shot 41
> Processing shot 17
> Processing shot 5
> Processing shot 29
> Processing shot 42
> Processing shot 18
> Processing shot 30
> Processing shot 6
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 35
> Processing shot 47
> Processing shot 23
> Processing shot 11
> Processing shot 0
> Processing shot 12
> Processing shot 36
> Processing shot 24
> Processing shot 1
> Processing shot 37
> Processing shot 25
> Processing shot 13
> Processing shot 2
> Processing shot 38
> Processing shot 26
> Processing shot 14
> Processing shot 39
> Processing shot 3
> Processing shot 27
> Processing shot 15
> Processing shot 40
> Processing shot 4
> Processing shot 28
> Processing shot 16
> Processing shot 41
> Processing shot 5
> Processing shot 29
> Processing shot 17
> Processing shot 42
> Processing shot 6
> Processing shot 30
> Processing shot 18
> Processing shot 43
> Processing shot 7
> Processing shot 31
> Processing shot 19
> Processing shot 44
> Processing shot 8
> Processing shot 32
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 36
> Processing shot 0
> Processing shot 12
> Processing shot 24
> Processing shot 37
> Processing shot 1
> Processing shot 13
> Processing shot 25
> Processing shot 38
> Processing shot 2
> Processing shot 14
> Processing shot 26
> Processing shot 39
> Processing shot 3
> Processing shot 27
> Processing shot 15
> Processing shot 40
> Processing shot 4
> Processing shot 28
> Processing shot 16
> Processing shot 41
> Processing shot 5
> Processing shot 29
> Processing shot 17
> Processing shot 42
> Processing shot 6
> Processing shot 30
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 36
> Processing shot 0
> Processing shot 12
> Processing shot 24
> Processing shot 37
> Processing shot 25
> Processing shot 1
> Processing shot 13
> Processing shot 38
> Processing shot 26
> Processing shot 2
> Processing shot 14
> Processing shot 39
> Processing shot 27
> Processing shot 3
> Processing shot 15
> Processing shot 40
> Processing shot 28
> Processing shot 4
> Processing shot 16
> Processing shot 41
> Processing shot 29
> Processing shot 5
> Processing shot 17
> Processing shot 42
> Processing shot 30
> Processing shot 6
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 12
> Processing shot 36
> Processing shot 24
> Processing shot 0
> Processing shot 37
> Processing shot 13
> Processing shot 25
> Processing shot 1
> Processing shot 38
> Processing shot 14
> Processing shot 26
> Processing shot 2
> Processing shot 39
> Processing shot 27
> Processing shot 15
> Processing shot 3
> Processing shot 40
> Processing shot 28
> Processing shot 16
> Processing shot 4
> Processing shot 41
> Processing shot 29
> Processing shot 17
> Processing shot 5
> Processing shot 42
> Processing shot 30
> Processing shot 18
> Processing shot 6
> Processing shot 43
> Processing shot 31
> Processing shot 19
> Processing shot 7
> Processing shot 44
> Processing shot 32
> Processing shot 20
> Processing shot 8
> Processing shot 45
> Processing shot 33
> Processing shot 21
> Processing shot 9
> Processing shot 46
> Processing shot 34
> Processing shot 22
> Processing shot 10
> Processing shot 47
> Processing shot 35
> Processing shot 23
> Processing shot 11
> Processing shot 12
> Processing shot 0
> Processing shot 36
> Processing shot 24
> Processing shot 37
> Processing shot 1
> Processing shot 13
> Processing shot 25
> Processing shot 38
> Processing shot 2
> Processing shot 14
> Processing shot 26
> Processing shot 39
> Processing shot 3
> Processing shot 27
> Processing shot 15
> Processing shot 40
> Processing shot 28
> Processing shot 4
> Processing shot 16
> Processing shot 41
> Processing shot 29
> Processing shot 5
> Processing shot 17
> Processing shot 42
> Processing shot 30
> Processing shot 6
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 36
> Processing shot 0
> Processing shot 12
> Processing shot 24
> Processing shot 37
> Processing shot 1
> Processing shot 25
> Processing shot 13
> Processing shot 38
> Processing shot 26
> Processing shot 2
> Processing shot 14
> Processing shot 39
> Processing shot 27
> Processing shot 3
> Processing shot 15
> Processing shot 40
> Processing shot 28
> Processing shot 4
> Processing shot 16
> Processing shot 41
> Processing shot 29
> Processing shot 5
> Processing shot 17
> Processing shot 42
> Processing shot 30
> Processing shot 6
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 0
> Processing shot 12
> Processing shot 36
> Processing shot 24
> Processing shot 37
> Processing shot 13
> Processing shot 1
> Processing shot 25
> Processing shot 38
> Processing shot 26
> Processing shot 14
> Processing shot 2
> Processing shot 39
> Processing shot 27
> Processing shot 3
> Processing shot 15
> Processing shot 40
> Processing shot 28
> Processing shot 4
> Processing shot 16
> Processing shot 41
> Processing shot 29
> Processing shot 5
> Processing shot 17
> Processing shot 42
> Processing shot 30
> Processing shot 6
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 0
> Processing shot 36
> Processing shot 12
> Processing shot 24
> Processing shot 37
> Processing shot 1
> Processing shot 13
> Processing shot 25
> Processing shot 38
> Processing shot 2
> Processing shot 14
> Processing shot 26
> Processing shot 39
> Processing shot 3
> Processing shot 27
> Processing shot 15
> Processing shot 40
> Processing shot 4
> Processing shot 28
> Processing shot 16
> Processing shot 41
> Processing shot 5
> Processing shot 29
> Processing shot 17
> Processing shot 42
> Processing shot 6
> Processing shot 30
> Processing shot 18
> Processing shot 43
> Processing shot 7
> Processing shot 31
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> Processing shot 36
> Processing shot 0
> Processing shot 24
> Processing shot 12
> Processing shot 37
> Processing shot 1
> Processing shot 25
> Processing shot 13
> Processing shot 38
> Processing shot 2
> Processing shot 26
> Processing shot 14
> Processing shot 39
> Processing shot 27
> Processing shot 3
> Processing shot 15
> Processing shot 40
> Processing shot 28
> Processing shot 4
> Processing shot 16
> Processing shot 41
> Processing shot 29
> Processing shot 5
> Processing shot 17
> Processing shot 42
> Processing shot 30
> Processing shot 6
> Processing shot 18
> Processing shot 43
> Processing shot 31
> Processing shot 7
> Processing shot 19
> Processing shot 44
> Processing shot 32
> Processing shot 8
> Processing shot 20
> Processing shot 45
> Processing shot 33
> Processing shot 9
> Processing shot 21
> Processing shot 46
> Processing shot 34
> Processing shot 10
> Processing shot 22
> Processing shot 47
> Processing shot 35
> Processing shot 11
> Processing shot 23
> 
> ```
>        * * *
> ```
> 
> Tit = total number of iterations
> Tnf = total number of function evaluations
> Tnint = total number of segments explored during Cauchy searches
> Skip = number of BFGS updates skipped
> Nact = number of active bounds at final generalized Cauchy point
> Projg = norm of the final projected gradient
> F = final function value
> 
> ```
>        * * *
> ```
> 
> N Tit Tnf Tnint Skip Nact Projg F
> 51456 1 21 1 0 0 2.184D+04 3.094D-41
> F = 3.0942071390756286E-041
> 
> ABNORMAL_TERMINATION_IN_LNSRCH
> 
> Line search cannot locate an adequate point after 20 function
> and gradient evaluations. Previous x, f and g restored.
> Possible causes: 1 error in function or gradient evaluation;
> 2 rounding error dominate computation.

Hi, thank you for raising the issue. I suspect the c++ functionality changed in newer version of PyTorch. The misfit actually is not passed to the optimizer. Let me take a closer look.

**Comment by ADharaUTEXAS123007** [comment]
Hi Li

Thanks for looking into it. I am planning to use this code exhaustively for my research. Which version of pytorch did you use originally?

**Comment by lidongzh** [comment]
> Hi Li
> 
> Thanks for looking into it. I am planning to use this code exhaustively for my research. Which version of pytorch did you use originally?

Seems  PyTorch 1.5.0 works fine.

**Comment by lidongzh** [comment]
> Hi Li
> 
> Thanks for looking into it. I am planning to use this code exhaustively for my research. Which version of pytorch did you use originally?

Hi,

I fix the bug in passing the misfit to the optimizer. Could you check if the new version works on your side?

Dongzhuo

**Comment by lidongzh** [comment]
> Hi Li
> 
> Thanks for looking into it. I am planning to use this code exhaustively for my research. Which version of pytorch did you use originally?

Hi,

I've fixed the bug in passing the misfit to the optimizer. Could you check if the new version works on your side?

Dongzhuo

**Comment by ADharaUTEXAS123007** [comment]
Thanks Dongzhuo.
The code works now.
